export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="kolo"

ENABLE_CORRECTION="true"

plugins=(git django virtualenvwrapper mvn npm pip python history history-substring-search)

source $ZSH/oh-my-zsh.sh

workon sandbox

export REPOS_HOME=${HOME}/source

export JAVA_HOME=$(/usr/libexec/java_home)
export EDITOR=vim

alias grep='ggrep -n --color=auto'
alias pyserv='python -m SimpleHTTPServer'
alias ql='qlmanage -p 2>/dev/null'
alias c='clear'
alias svi='sudo vi'
alias nrd='sudo nginx -s reload'
alias nst='sudo nginx'
alias nsp='sudo nginx -s stop'
alias wget='wget -c'

upmaster() {
    pushd $REPOS_HOME > /dev/null 2>&1;
    echo '\nUpdating master branches'
    echo '------------------------'
    for repo in `ls`; do
        echo
        echo $repo...
        pushd $repo > /dev/null 2>&1
        if [ $(git rev-parse --abbrev-ref HEAD) != "master" ]; then 
            git checkout master
        fi
        git fetch --dry-run > /dev/null || git pull
        popd > /dev/null 2>&1
    done
    popd > /dev/null 2>&1
}
