export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="kolo"

ENABLE_CORRECTION="true"

plugins=(bower brew django git history history-substring-search httpie npm pip python supervisor virtualenvwrapper vagrant)

source $ZSH/oh-my-zsh.sh

export REPOS_HOME=${HOME}/source

alias vi=vim
export EDITOR=vim

alias grep='grep -n --color=auto'
alias pyserv='python -m SimpleHTTPServer'
alias ql='qlmanage -p 2>/dev/null'
alias c='clear'
alias svi='sudo vi'
alias nrd='sudo nginx -s reload'
alias nst='sudo nginx'
alias nsp='sudo nginx -s stop'
alias wget='wget -c'
alias gdi='git diff --ignore-all-space'
alias gcb='git checkout -b'
alias grp='git grep -n'
alias upip='pip freeze --local | \grep -v "^\-e" | cut -d = -f 1  | xargs -n1 pip install -U'
alias gcu='git gc --aggressive'

upr() {
    local repo=$1
    local padded_repo_name_len=$((${#repo}+2))
    echo
    echo -n ╔
    printf '═%.0s' {1..$padded_repo_name_len}
    echo ╗
    echo "║ $repo ║"
    echo -n ╚
    printf '═%.0s' {1..$padded_repo_name_len}
    echo ╝
    cd $repo > /dev/null 2>&1
    local current_branch=$(git rev-parse --abbrev-ref HEAD)
    if [ $current_branch != "master" ]; then 
        echo Currently on branch $current_branch
        git stash
        git checkout master
    fi
    git pull
    git branch --merged | \grep -v "\*" | xargs -n 1 git branch -d
    cd - > /dev/null 2>&1
}

up() {
    local orig_dir=`pwd`
    cd $REPOS_HOME > /dev/null 2>&1;
    echo '\nUpdating repositories'
    echo '====================='
    for repo in `ls`; do
        upr $repo
    done
    cd $orig_dir > /dev/null 2>&1
}

guni() {
    local current_dir=`basename $(pwd)`
    if [ -d $current_dir ]; then
        if [ -f $current_dir/wsgi.py ]; then
            echo Serving $current_dir with gunicorn...
            gunicorn --reload -b 127.0.0.1:8080 $current_dir.wsgi &
        else
            echo "Error attempting to serve WSGI via gunicorn!"
        fi
    else
        echo "Error attempting to serve WSGI via gunicorn!"
    fi
}

look_for_process() {
    local ps_name=$1
    ps aux | grep -v grep | grep $ps_name
}

alias lfp='look_for_process'

alias upfork='git fetch upstream; git checkout master; git merge upstream/master'
