# File watching
brew "modd"
brew "watch"

# Databases
brew "sqlite"

# JavaScript / JSON
brew "jq"

# Python
brew "python"
brew "python3"
brew "readline"

# Shell
brew "zsh"

# File editing
brew "vim"

# Git[Hub]
brew "gh"
brew "git"
brew "pre-commit"

# Networking
brew "curl"
brew "httpie"
cask "ngrok"
brew "wget"

# General CLI tools
brew "asciinema"
brew "awscli"
brew "bat"
brew "cookiecutter"
brew "ctags"
brew "devd"
brew "direnv"
brew "fzf"
brew "gnupg"
brew "graphviz"
brew "helm"
brew "htop"
brew "modd"
brew "proselint"
brew "ripgrep"
brew "tree"
brew "watch"
brew "xz"
brew "yq"
brew "zlib"
brew "zoxide"

# Security
cask "keepassxc"

# Productivity
cask "alfred"
brew "starship"
