#!/usr/bin/env python

import os
import sys
import atexit
import readline
import rlcompleter

history_file_path = os.path.expanduser("~/.python_history")

def save_history(history_file_path=history_file_path):
    if sys.version_info.major > 2:
        import readline
        readline.write_history_file(history_file_path)

if sys.version_info.major > 2 and os.path.exists(history_file_path):
    readline.read_history_file(history_file_path)

atexit.register(save_history)
del os, atexit, readline, rlcompleter, save_history, history_file_path
