" use mouse if available
if has('mouse')
    set mouse=a
endif

set nocompatible

" colorscheme
set t_Co=256
colorscheme solarized
set background=dark
syntax on

" filetype-specific settings
set autoindent
set smartindent
filetype plugin on
filetype plugin indent on

set undofile
set undodir=~/.vim/undo

set number

set nowrap

nmap <Leader>p :set paste!<CR>
nmap <Leader>l :setlocal number!<CR>
nmap <Leader>r :setlocal relativenumber!<CR>

" search
set incsearch
set hlsearch
set ignorecase
set smartcase
nnoremap <Leader><space> :nohlsearch<CR>

" tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
imap <S-Tab> <C-o><<

nmap ; :

" prude mode
nmap <Up> <nop>
nmap <Down> <nop>
nmap <Left> <nop>
nmap <Right> <nop>

" scrolling
set sidescroll=1
set sidescrolloff=30
set scrolloff=3

set backspace=indent,eol,start
set listchars=tab:\|·,nbsp:~,trail:·,precedes:<,extends:>

set ruler

set nobackup
set noswapfile

nmap <space> /

nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" jump to previously opened line
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

set laststatus=2

set nofoldenable

" Set UTF-8 encoding for universal use
set encoding=utf-8
