export HOMEBREW_NO_ANALYTICS=1

export ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.zsh-custom

ZSH_THEME="kolo"

ENABLE_CORRECTION="true"

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)

DISABLE_UPDATE_PROMPT=true
export ITERM2_SQUELCH_MARK=1

plugins=( \
    brew \
    bundler \
    django \
    docker \
    gem \
    git \
    history \
    httpie \
    jira \
    kubectl \
    nvm \
    osx \
    pip \
    poetry \
    pyenv \
    python \
    redis-cli \
    rvm \
    screen \
    supervisor \
    z \
    zsh-syntax-highlighting \
    history-substring-search \
)

source $ZSH/oh-my-zsh.sh

setopt hist_ignore_all_dups
setopt hist_reduce_blanks

if [ -f $HOME/.aliases.zsh ]; then
    . $HOME/.aliases.zsh
fi

export REPOS_HOME=$HOME/source

if [ -f $HOME/.functions.zsh ]; then
    . $HOME/.functions.zsh
fi

if [ -f $HOME/.profile ]; then
    . $HOME/.profile
fi

export PYTHONSTARTUP=$HOME/.pystartup
export PYTHONDONTWRITEBYTECODE=1

export EDITOR=vim
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
export PATH="${HOME}/.rvm/bin:${PATH}" # Add RVM to PATH for scripting

ssh-add -A &>/dev/null

export PYENV_ROOT="${HOME}/.pyenv"

# added by travis gem
[ -f ${HOME}/.travis/travis.sh ] && source ${HOME}/.travis/travis.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export GPG_TTY=$(tty)

# poetry
export PATH="${HOME}/.poetry/bin:${PATH}"

# MySQL
export PATH="/usr/local/opt/mysql@5.7/bin:${PATH}"

# direnv
eval "$(direnv hook zsh)"
